#common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OGI1OTUzNWE3YmJiMTk5NDhmZjQ1YjBjMjhlY2IxOTJlNzY3M2Q2M2Q0YTY5OTFkMTNmYzNmOTdlNmYyNGUxYTcxYzMyMzBlZTg0ZDA1YjYzZGYzNWQ2MzE0OWYwMGYwYzdiMA==
  logging:
    logstash: # forward logs to ELK
      enabled: true
      host: jhipster-logstash
  metrics:
    logs: # report metrics in the logs
      enabled: true
      report-frequency: 60 # in seconds

management:
  metrics:
    export:
      prometheus:
        enabled: false
spring:
  zipkin:
    base-url: http://jhipster-zipkin:9411
    enabled: true
  sleuth:
    sampler:
      probability: 1 # report 100% of traces to Zipkin
eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
